export const icons = [
    'Meat by Artem Kovyazin from the Noun Project',
    'Milk And Egg by Artem Kovyazin from the Noun Project',
    'Fish by Artem Kovyazin from the Noun Project',
    'vegan by Guilherme Furtado from the Noun Project', 
    'lemon slice by Artem Kovyazin from the Noun Project',
    'Plate with Kosher by Thomas Helbig from the Noun Project', 
    'halal by Rauan from the Noun Project', 
    'dairy free by Olguioo from the Noun Project', 
    'nut free by Olguioo from the Noun Project', 
    'Seafood free by Olguioo from the Noun Project', 
    'soy free by Olguioo from the Noun Project', 
    'Gluten Free by Olguioo from the Noun Project', 
    'Oven Mitt by Emma Haywood Curzon from the Noun Project',
];