import {_getLanguageCode, VocabEnum} from "./Constants";
import LocalizedStrings from 'react-native-localization';
import moment from "moment";
import "moment/locale/ja";
import "moment/locale/fr";

moment.locale(_getLanguageCode());

export const allVocabulary = [
    {key: '0', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'allspice'},fr: {},ja: {}})},
    {key: '1', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'angelica'},fr: {},ja: {}})},
    {key: '2', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'aniseed'},fr: {},ja: {}})},
    {key: '3', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'aromatic'},fr: {},ja: {}})},
    {key: '4', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'bad'},fr: {},ja: {}})},
    {key: '5', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'balm'},fr: {},ja: {}})},
    {key: '6', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'basil'},fr: {},ja: {}})},
    {key: '7', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'bay leaves'},fr: {},ja: {}})},
    {key: '8', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'caraway'},fr: {},ja: {}})},
    {key: '9', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'cardamon'},fr: {},ja: {}})},
    {key: '10', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'carrot'},fr: {},ja: {}})},
    {key: '11', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'cinnamon'},fr: {},ja: {}})},
    {key: '12', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'clove'},fr: {},ja: {}})},
    {key: '13', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'coriander'},fr: {},ja: {}})},
    {key: '14', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'cumin'},fr: {},ja: {}})},
    {key: '15', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'dill'},fr: {},ja: {}})},
    {key: '16', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'elusive'},fr: {},ja: {}})},
    {key: '17', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'entrancing'},fr: {},ja: {}})},
    {key: '18', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'fenugreek'},fr: {},ja: {}})},
    {key: '19', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'floral'},fr: {},ja: {}})},
    {key: '20', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'fruity'},fr: {},ja: {}})},
    {key: '21', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'garlic'},fr: {},ja: {}})},
    {key: '22', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'ginger'},fr: {},ja: {}})},
    {key: '23', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'horseradish'},fr: {},ja: {}})},
    {key: '24', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'hot'},fr: {},ja: {}})},
    {key: '25', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'lemon'},fr: {},ja: {}})},
    {key: '26', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'lemongrass'},fr: {},ja: {}})},
    {key: '27', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'mint'},fr: {},ja: {}})},
    {key: '28', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'mustard'},fr: {},ja: {}})},
    {key: '29', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'nutmeg'},fr: {},ja: {}})},
    {key: '30', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'onion'},fr: {},ja: {}})},
    {key: '31', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'orange'},fr: {},ja: {}})},
    {key: '32', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'paprika'},fr: {},ja: {}})},
    {key: '33', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'parsley'},fr: {},ja: {}})},
    {key: '34', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'pepper'},fr: {},ja: {}})},
    {key: '35', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'phenolic'},fr: {},ja: {}})},
    {key: '36', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'pimento'},fr: {},ja: {}})},
    {key: '37', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'rosemary'},fr: {},ja: {}})},
    {key: '38', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'saffron'},fr: {},ja: {}})},
    {key: '39', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'shallot'},fr: {},ja: {}})},
    {key: '40', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'spicy'},fr: {},ja: {}})},
    {key: '41', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'star anise'},fr: {},ja: {}})},
    {key: '42', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'suave'},fr: {},ja: {}})},
    {key: '43', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'tarragon'},fr: {},ja: {}})},
    {key: '44', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'vanilla'},fr: {},ja: {}})},

    {key: '45', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'acid'},fr: {},ja: {}})},
    {key: '46', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'acidulated'},fr: {},ja: {}})},
    {key: '47', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'acrid'},fr: {},ja: {}})},
    {key: '48', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'bitter'},fr: {},ja: {}})},
    {key: '49', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'bitter-sweet'},fr: {},ja: {}})},
    {key: '50', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'burning'},fr: {},ja: {}})},
    {key: '51', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'burnt'},fr: {},ja: {}})},
    {key: '52', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'earthy'},fr: {},ja: {}})},
    {key: '53', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'fermented'},fr: {},ja: {}})},
    {key: '54', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'fish'},fr: {},ja: {}})},
    {key: '55', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'fresh'},fr: {},ja: {}})},
    {key: '56', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'fruity'},fr: {},ja: {}})},
    {key: '57', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'ginger'},fr: {},ja: {}})},
    {key: '58', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'hazelnut'},fr: {},ja: {}})},
    {key: '59', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'heady'},fr: {},ja: {}})},
    {key: '60', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'horseradish'},fr: {},ja: {}})},
    {key: '61', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'insipid'},fr: {},ja: {}})},
    {key: '62', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'menthol'},fr: {},ja: {}})},
    {key: '63', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'mustard'},fr: {},ja: {}})},
    {key: '64', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'oily'},fr: {},ja: {}})},
    {key: '65', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'onion'},fr: {},ja: {}})},
    {key: '66', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'refreshing'},fr: {},ja: {}})},
    {key: '67', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'salty'},fr: {},ja: {}})},
    {key: '68', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'sour'},fr: {},ja: {}})},
    {key: '69', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'spicy'},fr: {},ja: {}})},
    {key: '70', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'stunning'},fr: {},ja: {}})},
    {key: '71', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'syrupy'},fr: {},ja: {}})},
    {key: '72', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'woody'},fr: {},ja: {}})},

    {key: '73', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'brittle'},fr: {},ja: {}})},
    {key: '74', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'broken'},fr: {},ja: {}})},
    {key: '75', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'creamy'},fr: {},ja: {}})},
    {key: '76', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'crispy'},fr: {},ja: {}})},
    {key: '77', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'crusty'},fr: {},ja: {}})},
    {key: '78', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'dense'},fr: {},ja: {}})},
    {key: '79', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'dried'},fr: {},ja: {}})},
    {key: '80', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'elastic'},fr: {},ja: {}})},
    {key: '81', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'fibrous'},fr: {},ja: {}})},
    {key: '82', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'firm'},fr: {},ja: {}})},
    {key: '83', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'flowing'},fr: {},ja: {}})},
    {key: '84', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'foamy'},fr: {},ja: {}})},
    {key: '85', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'fried'},fr: {},ja: {}})},
    {key: '86', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'frothy'},fr: {},ja: {}})},
    {key: '87', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'gelatinous'},fr: {},ja: {}})},
    {key: '88', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'grainy'},fr: {},ja: {}})},
    {key: '89', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'hard'},fr: {},ja: {}})},
    {key: '90', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'lumpy'},fr: {},ja: {}})},
    {key: '91', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'mealy'},fr: {},ja: {}})},
    {key: '92', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'mellow'},fr: {},ja: {}})},
    {key: '93', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'melting'},fr: {},ja: {}})},
    {key: '94', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'moist'},fr: {},ja: {}})},
    {key: '95', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'oily'},fr: {},ja: {}})},
    {key: '96', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'plastery'},fr: {},ja: {}})},
    {key: '97', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'powdery'},fr: {},ja: {}})},
    {key: '98', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'robust'},fr: {},ja: {}})},
    {key: '99', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'rubbery'},fr: {},ja: {}})},
    {key: '100', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'sandy'},fr: {},ja: {}})},
    {key: '101', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'savory'},fr: {},ja: {}})},
    {key: '102', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'silky'},fr: {},ja: {}})},
    {key: '103', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'sleek'},fr: {},ja: {}})},
    {key: '104', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'slimy'},fr: {},ja: {}})},
    {key: '105', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'smooth'},fr: {},ja: {}})},
    {key: '106', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'soft'},fr: {},ja: {}})},
    {key: '107', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'soggy'},fr: {},ja: {}})},
    {key: '108', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'sparkling'},fr: {},ja: {}})},
    {key: '109', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'spongy'},fr: {},ja: {}})},
    {key: '110', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'sticky'},fr: {},ja: {}})},
    {key: '111', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'streaky'},fr: {},ja: {}})},
    {key: '112', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'stringy'},fr: {},ja: {}})},
    {key: '113', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'syrupy'},fr: {},ja: {}})},
    {key: '114', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'tempera'},fr: {},ja: {}})},
    {key: '115', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'tender'},fr: {},ja: {}})},
    {key: '116', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'thick'},fr: {},ja: {}})},
    {key: '117', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'tight'},fr: {},ja: {}})},
    {key: '118', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'tough'},fr: {},ja: {}})},
    {key: '119', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'velvety'},fr: {},ja: {}})},
];