import {_getLanguageCode, VocabEnum} from "./Constants";
import LocalizedStrings from 'react-native-localization';
import moment from "moment";
import "moment/locale/ja";
import "moment/locale/fr";

moment.locale(_getLanguageCode());

export const allVocabulary = [
    {key: '0', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'allspice'},ja: {},fr: {}})},
    {key: '1', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'angelica'},ja: {},fr: {}})},
    {key: '2', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'aniseed'},ja: {},fr: {}})},
    {key: '3', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'aromatic'},ja: {},fr: {}})},
    {key: '4', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'bad'},ja: {},fr: {}})},
    {key: '5', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'balm'},ja: {},fr: {}})},
    {key: '6', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'basil'},ja: {},fr: {}})},
    {key: '7', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'bay leaves'},ja: {},fr: {}})},
    {key: '8', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'caraway'},ja: {},fr: {}})},
    {key: '9', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'cardamon'},ja: {},fr: {}})},
    {key: '10', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'carrot'},ja: {},fr: {}})},
    {key: '11', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'cinnamon'},ja: {},fr: {}})},
    {key: '12', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'clove'},ja: {},fr: {}})},
    {key: '13', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'coriander'},ja: {},fr: {}})},
    {key: '14', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'cumin'},ja: {},fr: {}})},
    {key: '15', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'dill'},ja: {},fr: {}})},
    {key: '16', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'elusive'},ja: {},fr: {}})},
    {key: '17', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'entrancing'},ja: {},fr: {}})},
    {key: '18', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'fenugreek'},ja: {},fr: {}})},
    {key: '19', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'floral'},ja: {},fr: {}})},
    {key: '20', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'fruity'},ja: {},fr: {}})},
    {key: '21', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'garlic'},ja: {},fr: {}})},
    {key: '22', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'ginger'},ja: {},fr: {}})},
    {key: '23', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'horseradish'},ja: {},fr: {}})},
    {key: '24', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'hot'},ja: {},fr: {}})},
    {key: '25', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'lemon'},ja: {},fr: {}})},
    {key: '26', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'lemongrass'},ja: {},fr: {}})},
    {key: '27', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'mint'},ja: {},fr: {}})},
    {key: '28', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'mustard'},ja: {},fr: {}})},
    {key: '29', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'nutmeg'},ja: {},fr: {}})},
    {key: '30', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'onion'},ja: {},fr: {}})},
    {key: '31', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'orange'},ja: {},fr: {}})},
    {key: '32', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'paprika'},ja: {},fr: {}})},
    {key: '33', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'parsley'},ja: {},fr: {}})},
    {key: '34', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'pepper'},ja: {},fr: {}})},
    {key: '35', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'phenolic'},ja: {},fr: {}})},
    {key: '36', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'pimento'},ja: {},fr: {}})},
    {key: '37', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'rosemary'},ja: {},fr: {}})},
    {key: '38', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'saffron'},ja: {},fr: {}})},
    {key: '39', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'shallot'},ja: {},fr: {}})},
    {key: '40', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'spicy'},ja: {},fr: {}})},
    {key: '41', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'star anise'},ja: {},fr: {}})},
    {key: '42', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'suave'},ja: {},fr: {}})},
    {key: '43', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'tarragon'},ja: {},fr: {}})},
    {key: '44', type: VocabEnum.ODOR, value: new LocalizedStrings({en: {name: 'vanilla'},ja: {},fr: {}})},


    {key: '45', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'acid'},ja: {name: '酸性'},fr: {name: 'acide'}})},
    {key: '46', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'acidulated'},ja: {},fr: {}})},
    {key: '47', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'acrid'},ja: {name: 'アクリド'},fr: {name: 'âcre'}})},
    {key: '48', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'bitter'},ja: {name: '苦い'},fr: {name: 'amer'}})},
    {key: '49', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'bitter-sweet'},ja: {name: 'ほろ苦い'},fr: {name: 'doux-amer'}})},
    {key: '50', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'burning'},ja: {},fr: {}})},
    {key: '51', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'burnt'},ja: {name: '燃え尽きる'},fr: {name: 'brûlé'}})},
    {key: '52', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'earthy'},ja: {},fr: {}})},
    {key: '53', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'fermented'},ja: {},fr: {}})},
    {key: '54', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'fish'},ja: {},fr: {}})},
    {key: '55', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'fresh'},ja: {},fr: {}})},
    {key: '56', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'fruity'},ja: {},fr: {}})},
    {key: '57', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'ginger'},ja: {},fr: {}})},
    {key: '58', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'hazelnut'},ja: {},fr: {}})},
    {key: '59', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'heady'},ja: {},fr: {}})},
    {key: '60', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'horseradish'},ja: {},fr: {}})},
    {key: '61', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'insipid'},ja: {},fr: {}})},
    {key: '62', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'menthol'},ja: {},fr: {}})},
    {key: '63', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'mustard'},ja: {},fr: {}})},
    {key: '64', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'oily'},ja: {},fr: {}})},
    {key: '65', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'onion'},ja: {},fr: {}})},
    {key: '66', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'refreshing'},ja: {},fr: {}})},
    {key: '67', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'salty'},ja: {},fr: {}})},
    {key: '68', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'sour'},ja: {},fr: {}})},
    {key: '69', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'spicy'},ja: {},fr: {}})},
    {key: '70', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'stunning'},ja: {},fr: {}})},
    {key: '71', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'syrupy'},ja: {},fr: {}})},
    {key: '72', type: VocabEnum.TASTE, value: new LocalizedStrings({en: {name: 'woody'},ja: {},fr: {}})},


    {key: '73', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'brittle'},ja: {},fr: {}})},
    {key: '74', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'broken'},ja: {},fr: {}})},
    {key: '75', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'creamy'},ja: {},fr: {}})},
    {key: '76', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'crispy'},ja: {},fr: {}})},
    {key: '77', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'crusty'},ja: {},fr: {}})},
    {key: '78', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'dense'},ja: {},fr: {}})},
    {key: '79', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'dried'},ja: {},fr: {}})},
    {key: '80', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'elastic'},ja: {},fr: {}})},
    {key: '81', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'fibrous'},ja: {},fr: {}})},
    {key: '82', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'firm'},ja: {},fr: {}})},
    {key: '83', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'flowing'},ja: {},fr: {}})},
    {key: '84', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'foamy'},ja: {},fr: {}})},
    {key: '85', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'fried'},ja: {},fr: {}})},
    {key: '86', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'frothy'},ja: {},fr: {}})},
    {key: '87', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'gelatinous'},ja: {},fr: {}})},
    {key: '88', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'grainy'},ja: {},fr: {}})},
    {key: '89', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'hard'},ja: {},fr: {}})},
    {key: '90', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'lumpy'},ja: {},fr: {}})},
    {key: '91', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'mealy'},ja: {},fr: {}})},
    {key: '92', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'mellow'},ja: {},fr: {}})},
    {key: '93', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'melting'},ja: {},fr: {}})},
    {key: '94', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'moist'},ja: {},fr: {}})},
    {key: '95', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'oily'},ja: {},fr: {}})},
    {key: '96', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'plastery'},ja: {},fr: {}})},
    {key: '97', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'powdery'},ja: {},fr: {}})},
    {key: '98', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'robust'},ja: {},fr: {}})},
    {key: '99', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'rubbery'},ja: {},fr: {}})},
    {key: '100', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'sandy'},ja: {},fr: {}})},
    {key: '101', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'savory'},ja: {},fr: {}})},
    {key: '102', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'silky'},ja: {},fr: {}})},
    {key: '103', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'sleek'},ja: {},fr: {}})},
    {key: '104', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'slimy'},ja: {},fr: {}})},
    {key: '105', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'smooth'},ja: {},fr: {}})},
    {key: '106', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'soft'},ja: {},fr: {}})},
    {key: '107', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'soggy'},ja: {},fr: {}})},
    {key: '108', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'sparkling'},ja: {},fr: {}})},
    {key: '109', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'spongy'},ja: {},fr: {}})},
    {key: '110', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'sticky'},ja: {},fr: {}})},
    {key: '111', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'streaky'},ja: {},fr: {}})},
    {key: '112', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'stringy'},ja: {},fr: {}})},
    {key: '113', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'syrupy'},ja: {},fr: {}})},
    {key: '114', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'tempera'},ja: {},fr: {}})},
    {key: '115', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'tender'},ja: {},fr: {}})},
    {key: '116', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'thick'},ja: {},fr: {}})},
    {key: '117', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'tight'},ja: {},fr: {}})},
    {key: '118', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'tough'},ja: {},fr: {}})},
    {key: '119', type: VocabEnum.TEXTURE, value: new LocalizedStrings({en: {name: 'velvety'},ja: {},fr: {}})},
];