import LocalizedStrings from 'react-native-localization';
import {getLanguageCode} from './Constants/Constants';
import moment from "moment";
import "moment/locale/ja";
import "moment/locale/fr";
import "moment/locale/pt";
import "moment/locale/de";
import "moment/locale/ta";

moment.locale(getLanguageCode());

// Get/change translations here: https://docs.google.com/spreadsheets/d/1JXiic2aAk2YrC53YfQs0_XKjRLzOpmVa6DNIK7LdaWg/edit?usp=sharing

// Use the translation:
// Add this to the top of the file: import strings from "../strings";
// Use a string like so: strings.home
// If you add another language: add the language code (e.g. de) to the locales above and add the translations like below

export const appName = 'Flavorlens';

export default strings = new LocalizedStrings({
    en: {
        home: 'Home',
        explore: 'Explore',
        notifications: 'Notifications',
        eatingOutList: 'Eating Out List',
        profile: 'Profile',
        settings: 'Settings',
        observationDetail: 'Detail',
        createObservation: 'Create Observation',
        signUpLogIn: 'Sign Up Log In',
        mapDetail: 'Map Detail',
        hiThere: 'Hi there,',
        welcomeToTastemate: 'Welcome to {0}!',
        limitedContentExplanation: 'Unfortunately, you\'re not logged in, so we can only show you limited content and functionality. Once you\'re ready to explore more of the app, click the user icon button in the top left corner to log in or create a new account. In the meantime,',
        haveFun: 'Have fun!',
        emptyFeed: 'Seems like your feed is empty. Why not follow some tastemates?',
        selectAction: 'Select an action',
        doWithPost: 'What would you like to do with this post?',
        share: 'Share',
        edit: 'Edit',
        delete: 'Delete',
        cancel: 'Cancel',
        shareDialogTitle: 'Where do you want to share this post?',
        shareSubject: 'Cool Dish on {0}',
        shareMessage: 'Look at this awesome dish on {0}!',
        likes: '{0} likes',
        shares: '{0} shares',
        cutleries: '{0} cutleries',
        likesSg: '{0} like',
        sharesSg: '{0} share',
        cutleriesSg: '{0} cutlery',
        thousand: '{0}k',
        million: '{0}m',
        writeComment: 'Write a comment...',
        close: 'Close',
        likedPicture: '{0} liked your picture.',
        sharedPicture: '{0} shared your picture.',
        addedToEatingOutPicture: '{0} added your picture to their Eating Out list.',
        startedFollowing: '{0} started following you.',
        userAndUser: '{0} and {1}',
        others: '{0} others',
        photos: 'Photos',
        followers: 'Followers',
        following: 'Following',
        noPictures: 'This user has not added any pictures.',
        noUsers: 'No users to display.',
        foodCraving: 'What food are you craving?',
        username: 'Username',
        emailAddress: 'Email address',
        location: 'Location',
        oldPassword: 'Old password',
        newPassword: 'New password',
        newPasswordRepeat: 'New password (repeat)',
        notifyMe: 'Notify me when...',
        likesPicture: 'someone likes my picture',
        addsToEatingOutPicture: 'someone adds my picture to their Eating Out list',
        sharesPicture: 'someone shares my picture',
        startsFollowing: 'someone starts following me',
        saveChanges: 'Save Changes',
        list: 'List',
        map: 'Map',
        noEatingOut: 'Seems like you have not added a dish to your list. Just click the cutlery icon to do so!',
        welcomeTo: 'Welcome to',
        tastemateDescription: 'the place to share your culinary experiences with others',
        getEating: 'Let\'s get eating!',
        signUp: 'Sign Up',
        logIn: 'Log In',
        password: 'Password',
        noAccount: 'Don\'t have an account yet? Sign up here!',
        alreadyAccount: 'Already have an account? Log in here!',
        skip: 'Skip',
        errorMessageEnterUsername: 'Please enter a username.',
        errorMessageEnterEmail: 'Please enter an email address.',
        errorMessageEnterPassword: 'Please enter a password.',
        errorMessageEnterLocation: 'Please enter a location.',
        errorMessageInvalidEmail: 'The email address you entered is invalid.',
        errorMessageUserDisabled: 'The account associated with this email address has been disabled.',
        errorMessageUserNotFound: 'There is no account associated with this email address.',
        errorMessageWrongPassword: 'The password you entered is incorrect.',
        errorMessageWeakPassword: 'The password you entered is too weak.',
        errorMessageEmailAlreadyInUse: 'This email address is already connected to a {0} account.',
        next: 'Next',
        previous: 'Previous',
        publish: 'Publish',
        description: 'Description',
        dishname: 'Dish name',
        price: 'Price',
        rateExperience: 'How would you rate your overall experience?',
        currency: 'Currency',
        selectCurrency: 'Please select the currency of the price you stated.',
        searchVocabulary: 'What was the taste, texture, and odor of the dish?',
        noLocationResults: 'No matching location found, please enter more information.',
        yes: 'Yes',
        no: 'No',
        ok: 'OK',
        openSettings: 'Open Settings',
        accessCameraQuestion: 'May we access your camera?',
        accessCameraExplanation: 'We need access so you can take and share pictures of your food.',
        accessPhotoQuestion: 'May we access your photo roll?',
        accessPhotoExplanation: 'We need access so you can select and share pictures of your food.',
        enableCamera: 'Please enable the camera permission in the {0} settings of your phone to use this feature.',
        enablePhoto: 'Please enable the storage permission in the {0} settings of your phone to use this feature.',
        enableCameraAndPhoto: 'To upload a picture, we first need access to your camera and to the camera roll. Please click here to open the permission dialog! Alternatively, you can go to the {0} settings of your smartphone and grant the permissions there.',
        permissionDenied: 'Permission Denied',
        mypocExplanationTitle: 'The MyPoC Text Field',
        mypocExplanationText: 'This field displays a general dish name as predicted by our MyPoC system. Feel free to edit the name if the prediction is incorrect!',
        more: 'More',
        accessLocationQuestion: 'May we access your location?',
        accessLocationExplanation: 'We need access so you can see which saved observations are nearby.',
        enableLocation: 'Please enable the location permission in the {0} settings of your phone to use this feature.',
        editObservation: 'Edit Observation',
        save: 'Save',
        errorMessageUsernameAlreadyInUse: 'This username is already connected to a {0} account.',
        commentsSg: '{0} comment',
        comments: '{0} comments',
        commentedPicture: '{0} commented on your picture.',
        allComments: 'All Comments',
        missingValuesTitle: 'Missing Values',
        missingValuesTextSg: 'Please add the {0} of your dish before publishing it.',
        missingValuesTextPl: 'Please add the {0} and {1} of your dish before publishing it.',
        itemization: '{0}, {1}',
        picture: 'Picture',
        tasteTerms: '1 taste term',
        lessThanKm: 'Less than {0}km away',
        furtherAway: 'Further away',
        noEatingOutList: 'Looks like you haven\'t added anything to your Eating Out list. Just click the cutlery icon next to an observation to add it to the list!',
        noNotifications: 'You do not have any notifications yet.',
        noImages: 'Looks like your camera roll is empty. Try taking a picture instead.',
        checkingUsername: 'Checking if username is already taken...',
        creatingAccount: 'Creating your account...',
        savingUserInformation: 'Saving your information...',
        loggingIn: 'Logging you in...',
        creatingAnonymous: 'Creating an anonymous account...',
        savingObservation: 'Saving observation...',
        savingProfile: 'Saving profile...',
        uploadingPicture: 'Uploading picture...',
        unknownLocation: 'Unknown location',
        loading: 'Loading...',
        errorOccurred: 'An error occurred. Please try again later.',
        noSearchResults: 'There are no observations that match your search. Please enter something else.',
        viewMoreComments: 'View more comments',
        flavor: 'Flavor',
        odor: 'Odor',
        texture: 'Texture',
        selected: 'Selected',
        noMatchingTerms: 'There are no terms that match your search.',
        noSelectedTerms: 'Click on one of the terms below to add it to your observation.',
        myPoc: 'MyPoC suggestion: {0}',
        all: 'All',
        dietaryInfo: 'Dietary information',
        homemade: 'Homemade',
        eatingOut: 'Eating out',
        viewAttributions: 'View Attributions',
        attributions: 'Attributions',
        predictionLoading: 'MyPoC suggestion loading...',
        mypocPrediction: 'MyPoC suggestion',
        exitCreateAlertTitle: 'Save As Draft?',
        exitCreateAlertMessage: 'You\'re about to exit the Creation screen. Would you like to save your current progress as a draft?',
        discard: 'Discard',
        saveDraft: 'Save Draft',
        deleteDraftAlertTitle: 'Delete Draft?',
        deleteDraftAlertMessage: 'Are you sure you want to delete this draft? This action is irreversible. ',
        deleteDraft: 'Delete Draft',
        noDrafts: 'You have not saved any observations as drafts.',
        readMore: 'Read More',
        hide: 'Hide',
        noInternetAlertTitle: 'No Internet Connection',
        noInternetAlertMessage: 'Please connect your phone to the Internet to proceed.',
        unknownUsername: 'Unknown username',
        kFollowers: '{0} followers',
        kFollowersSg: '{0} follower',
        clickHereToRefresh: 'Simply click here to refresh your feed once you\'re done!',
        noInternet: 'Seems like you\'re not connected to the Internet. Please connect to get the most recent data.',
        tryAgain: 'Try Again',
        none: 'None',
        fruitarian: 'Fruitarian',
        vegetarian: 'Vegetarian',
        pescatarian: 'Pescatarian',
        vegan: 'Vegan',
        noLactose: 'Lactose-Free',
        noNut: 'Nut-Free',
        noEgg: 'Egg-Free',
        noSoy: 'Soy-Free',
        noFish: 'Fish-Free',
        noShellfish: 'Shellfish-Free',
        kosher: 'Kosher',
        halal: 'Halal',
        glutenFree: 'Gluten-Free',
        basil: 'basil',
        bitter: 'bitter',
        bitterSweet: 'bitter-sweet',
        burnt: 'burnt',
        cinnamon: 'cinnamon',
        coriander: 'coriander',
        cumin: 'cumin',
        dill: 'dill',
        fishy: 'fishy',
        floral: 'floral',
        fresh: 'fresh',
        fruity: 'fruity',
        garlic: 'garlic',
        gingery: 'gingery',
        lemon: 'lemon',
        nutmeg: 'nutmeg',
        nutty: 'nutty',
        oily: 'oily',
        oniony: 'oniony',
        orange: 'orange',
        paprika: 'paprika',
        parsley: 'parsley',
        pepper: 'pepper',
        rosemary: 'rosemary',
        salty: 'salty',
        sour: 'sour',
        spicy: 'spicy',
        sweet: 'sweet',
        umami: 'umami',
        vanilla: 'vanilla',
        xOptional: '{0} (Optional)'
    },
    fr: {
        explore: 'Explorer',
        notifications: 'Notifications',
        eatingOutList: 'Eating Out List',
        profile: 'Profile',
        settings: 'Paramètres',
        observationDetail: 'Détail',
        createObservation: 'Créer une observation',
        signUpLogIn: 'Inscription Connexion',
        mapDetail: 'Détails de la carte',
        hiThere: 'Salut',
        welcomeToTastemate: 'Bienvenue à {0}!',
        limitedContentExplanation: 'Malheureusement, vous n\'êtes pas connecté, nous ne pouvons vous montrer que du contenu et des fonctionnalités limités. Une fois que vous êtes prêt à explorer plus l\'application, cliquez sur le bouton de l\'icône utilisateur dans le coin supérieur gauche pour vous connecter ou créer un nouveau compte. Pendant ce temps,',
        haveFun: 'Amusez-vous!',
        emptyFeed: 'Votre flux semble être vide. Pourquoi ne pas suivre quelques dégustations?',
        selectAction: 'Sélectionnez une action',
        doWithPost: 'Que voudriez-vous faire avec ce post?',
        share: 'Partage',
        edit: 'Modifier',
        delete: 'Supprimer',
        cancel: 'Annuler',
        shareDialogTitle: 'Où voulez-vous partager ce post?',
        shareSubject: 'Cool Dish sur {0}',
        shareMessage: 'Regardez ce plat impressionnant sur {0}!',
        likes: '{0} aime',
        shares: '{0} partages',
        cutleries: '{0} couverts',
        likesSg: '{0} aime',
        sharesSg: '{0} partage',
        cutleriesSg: '{0} coutellerie',
        thousand: '{0}k',
        million: '{0}m',
        writeComment: 'Ecrire un commentaire ...',
        close: 'Fermer',
        likedPicture: '{0} a aimé votre photo.',
        sharedPicture: '{0} a partagé votre photo..',
        addedToEatingOutPicture: '{0} a ajouté votre image à sa liste Eating Out.',
        startedFollowing: '{0} a commencé à vous suivre.',
        userAndUser: '{0} et {1}',
        others: '{0} autres',
        photos: 'Photos',
        followers: 'Abonnés',
        following: 'Suivant',
        noPictures: 'Cet utilisateur n\'a ajouté aucune photo.',
        noUsers: 'Aucun utilisateur à afficher.',
        foodCraving: 'De quelle nourriture avez-vous envie ?',
        username: 'username',
        emailAddress: 'adresse email',
        location: 'location',
        oldPassword: 'ancien mot de passe',
        newPassword: 'nouveau mot de passe',
        newPasswordRepeat: 'nouveau mot de passe (répétition)',
        notifyMe: 'Prévenez-moi quand ...',
        likesPicture: 'quelqu\'un aime ma photo',
        addsToEatingOutPicture: 'quelqu\'un ajoute ma photo à sa liste Eating Out',
        sharesPicture: 'quelqu\'un partage ma photo',
        startsFollowing: 'quelqu\'un commence à me suivre',
        saveChanges: 'Enregistrer les modifications',
        list: 'Liste',
        map: 'Carte',
        noEatingOut: 'On dirait que vous n\'avez pas ajouté un plat à votre liste. Cliquez simplement sur l\'icône Couteau pour le faire!',
        welcomeTo: 'Bienvenue à',
        tastemateDescription: 'l\'endroit pour partager vos expériences culinaires avec les autres',
        getEating: 'Allons manger!',
        signUp: 'Inscription',
        logIn: 'Connexion',
        password: 'mot de passe',
        noAccount: 'Vous n\'avez pas encore de compte? Inscrivez-vous ici!',
        alreadyAccount: 'Vous avez déjà un compte? Connectez-vous ici!',
        skip: 'Skip',
        errorMessageEnterUsername: 'Veuillez entrer un nom d\'utilisateur.',
        errorMessageEnterEmail: 'Veuillez entrer une adresse e-mail.',
        errorMessageEnterPassword: 'Veuillez entrer un mot de passe.',
        errorMessageEnterLocation: 'Veuillez entrer un lieu.',
        errorMessageInvalidEmail: 'L\'adresse e-mail que vous avez entrée est invalide.',
        errorMessageUserDisabled: 'Le compte associé à cette adresse e-mail a été désactivé.',
        errorMessageUserNotFound: 'Aucun compte n\'est associé à cette adresse e-mail.',
        errorMessageWrongPassword: 'Le mot de passe que vous avez entré est incorrect.',
        errorMessageWeakPassword: 'Le mot de passe que vous avez entré est trop faible.',
        errorMessageEmailAlreadyInUse: 'Cette adresse e-mail est déjà connectée à un compte {0}.',
        next: 'Suivant',
        previous: 'Precedent',
        publish: 'Publish',
        description: 'description',
        dishname: 'nom de plat',
        price: 'prix',
        rateExperience: 'Comment évaluez-vous votre expérience majeure?',
        currency: 'Devise',
        selectCurrency: 'Veuillez sélectionner la devise du prix que vous avez indiqué.',
        searchVocabulary: 'Quels étaient le goût, la texture et l\'odeur du plat?',
        noLocationResults: 'Aucun emplacement correspondant trouvé, veuillez entrer plus d\'informations.',
        yes: 'Oui',
        no: 'Non',
        ok: 'OK',
        openSettings: 'Ouvrir les paramètres',
        accessCameraQuestion: 'Pouvons-nous accéder à votre caméra?',
        accessCameraExplanation: 'Nous avons besoin d\'un accès pour pouvoir prendre et partager des photos de votre nourriture.',
        accessPhotoQuestion: 'Pouvons-nous accéder à votre rouleau de photos?',
        accessPhotoExplanation: 'Nous avons besoin d\'un accès pour pouvoir sélectionner et partager des photos de votre nourriture.',
        enableCamera: 'Veuillez activer l\'autorisation de la caméra dans les paramètres {0} de votre téléphone pour utiliser cette fonction.',
        enablePhoto: 'Nous avons besoin d\'un accès pour pouvoir sélectionner et partager des photos de votre nourriture.',
        enableCameraAndPhoto: 'Veuillez activer l\'autorisation de stockage dans le paramètre {0} de votre téléphone pour utiliser cette fonctionnalité. S\'il vous plaît cliquez ici pour ouvrir la permission là. Vous pouvez aller aux paramètres {0} de votre smartphone et accorder les autorisations là.',
        permissionDenied: 'Autorisation refusée',
        mypocExplanationTitle: 'Le champ de texte MyPoC',
        mypocExplanationText: 'Ce champ affiche un nom de plat général comme prédit par notre système MyPoC. N\'hésitez pas à modifier le nom si la prédiction est incorrecte!',
        more: 'Plus',
        accessLocationQuestion: 'Pouvons-nous accéder à votre position?',
        accessLocationExplanation: 'Nous avons besoin d\'un accès pour voir quelles observations sont à proximité.',
        enableLocation: 'Veuillez activer l\'autorisation de localisation dans les paramètres {0}',
        editObservation: 'Modifier l\'observation',
        save: 'Enregistrer',
        errorMessageUsernameAlreadyInUse: 'Ce nom d\'utilisateur est déjà connecté à un compte {0}.',
        commentsSg: '{0} commentaire',
        comments: '{0} commentaires',
        commentedPicture: '{0} a commenté votre photo.',
        allComments: 'Tous les commentaires',
        missingValuesTitle: 'Valeurs manquantes',
        missingValuesTextSg: 'Veuillez ajouter le {0} de votre plat avant de le publier.',
        missingValuesTextPl: 'Veuillez ajouter le {0} et le {1} de votre plat avant de le publier.',
        itemization: '{0}, {1}',
        picture: 'image',
        tasteTerms: '1 terme gustatif',
        lessThanKm: 'Moins de {0} km',
        furtherAway: 'Plus loin',
        noEatingOutList: 'Apparemment, vous n\'avez rien ajouté à votre liste de restaurants. Il suffit de cliquer sur l\'icône de la coutellerie à côté d\'une observation pour l\'ajouter à la liste!',
        noNotifications: 'Vous n\'avez encore aucune notification.',
        noImages: 'Votre rouleau de caméra semble vide. Essayez de prendre une photo à la place.',
        checkingUsername: 'Vérifier si le nom d\'utilisateur est déjà pris ...',
        creatingAccount: 'Création de votre compte ....',
        savingUserInformation: 'Sauvegarder vos informations ...',
        loggingIn: 'Vous connecter à ...',
        creatingAnonymous: 'Créer un compte anonyme ...',
        savingObservation: 'Sauver l\'observation ...',
        savingProfile: 'Sauvegarder le profil ....',
        uploadingPicture: 'Télécharger l\'image ...',
        unknownLocation: 'Emplacement inconnu',
        loading: 'Chargement ...',
        errorOccurred: 'Une erreur est survenue. Veuillez réessayer plus tard.',
        noSearchResults: 'Aucune observation ne correspond à votre recherche. S\'il vous plaît entrer quelque chose d\'autre.',
        viewMoreComments: 'Afficher plus de commentaires',
        flavor: 'Saveur',
        odor: 'Odeur',
        texture: 'Texture',
        selected: 'Sélectionné',
        noMatchingTerms: 'Aucun terme ne correspond à votre recherche.',
        noSelectedTerms: 'Cliquez sur l\'un des termes ci-dessous pour l\'ajouter à votre observation.',
        all: 'Suggestion de MyPoc: {0}',
        dietaryInfo: 'Informations diététiques',
        homemade: 'Fait maison',
        eatingOut: 'Manger à l\'extérieur',
        viewAttributions: 'Afficher les attributs',
        attributions: 'Attributs',
        predictionLoading: 'Chargement de la suggestion de MyPoC',
        mypocPrediction: 'Suggestion MyPoC',
        exitCreateAlertTitle: 'Enregistrer comme brouillon?',
        exitCreateAlertMessage: 'Vous êtes sur le point de quitter l\'écran de création. Voulez-vous enregistrer votre progression actuelle en tant que brouillon?',
        discard: 'Jeter',
        saveDraft: 'Enregistrer brouillon',
        deleteDraftAlertTitle: 'Supprimer le brouillon?',
        deleteDraftAlertMessage: 'Êtes-vous sûr de vouloir supprimer ce brouillon? Cette action est irréversible.',
        deleteDraft: 'Supprimer le brouillon',
        noDrafts: 'Vous n\'avez enregistré aucune observation en tant que brouillons.',
        readMore: 'Lire la suite',
        hide: 'Cacher',
        noInternetAlertTitle: 'Pas de connexion Internet',
        noInternetAlertMessage: 'Veuillez connecter votre téléphone à Internet pour continuer.',
        unknownUsername: 'Nom d\'utilisateur inconnu',
        kFollowers: '{0} abonnés',
        kFollowersSg: '{0} suiveur',
        clickHereToRefresh: 'Il suffit de cliquer ici pour actualiser votre flux une fois que vous avez terminé!',
        noInternet: 'On dirait que vous n\'êtes pas connecté à Internet. Veuillez vous connecter pour obtenir les données les plus récentes.',
        basil: 'basilic',
        bitter: 'amer',
        bitterSweet: 'doux-amer',
        burnt: 'brûlé',
        cinnamon: 'cannelle',
        coriander: 'coriandre',
        cumin: 'cumin',
        dill: 'aneth',
        fishy: 'de poisson',
        floral: 'floral',
        fresh: 'frais',
        fruity: 'fruité',
        garlic: 'ail',
        gingery: 'gout de gingembre',
        lemon: 'citron',
        nutmeg: 'noix de muscade',
        nutty: 'noisette',
        oily: 'huileux',
        oniony: 'gout d’onion',
        orange: 'orange',
        paprika: 'paprika',
        parsley: 'persil',
        pepper: 'poivre',
        rosemary: 'rosmarin',
        salty: 'alé',
        sour: 'acide',
        spicy: 'epicé',
        sweet: 'doux',
        umami: 'umami',
        vanilla: 'vanille',
    },
    ja: {
        home: 'ホーム',
        explore: 'エクスプローラー',
        notifications: '通知',
        eatingOutList: '食べるリスト',
        profile: 'プロフィール',
        settings: '設定',
        observationDetail: '詳細',
        createObservation: '観察を作成する',
        signUpLogIn: 'サインアップログイン',
        mapDetail: 'マップ詳細',
        hiThere: 'こんにちは、みなさん',
        welcomeToTastemate: '{0}にようこそ！',
        limitedContentExplanation: 'あなたはログインできません。従って、制限された内容と機能のみ使えます。いったんあなたがアプリをダウンロードする時は、ログインするために、左上コーナーのユーザーアイコンボタンをクリックするか、または新規作成してください。',
        haveFun: '楽しみなさい！',
        emptyFeed: 'あなたのフィードは空のようです。いくつかのtastematesに従いなさい',
        selectAction: '行動を選びなさい',
        doWithPost: 'この投稿を使って何をしたいですか',
        share: '共有',
        edit: '編集しなさい',
        delete: '削除しなさい',
        cancel: '取消し',
        shareDialogTitle: 'あなたはどこでこのポストを共有したいか？',
        shareSubject: '{0}の冷たい皿',
        shareMessage: '{0}のこの素晴らしい皿を見なさい！',
        likes: '{0} は望む',
        shares: '{0} は分担する',
        cutleries: '{0} 刃物',
        likesSg: '{0} は望む',
        sharesSg: '{0} は分担する',
        cutleriesSg: '{0} 刃物類',
        thousand: '{0}k',
        million: '{0}m',
        writeComment: 'コメントを書きなさい…',
        close: '閉じる',
        likedPicture: '{0} はあなたの写真が好き',
        sharedPicture: '{0} はあなたの写真を共有した',
        addedToEatingOutPicture: '{0} はあなたの写真を彼らの食べるリストに追加した',
        startedFollowing: '{0} はあなたをフォローした',
        userAndUser: '{0} および {1}',
        others: '{0} 他のもの',
        photos: '写真',
        followers: 'フォロワー',
        following: '後続',
        noPictures: 'このユーザーは少しの写真も追加しなかった。.',
        noUsers: '表示するユーザーはいません。',
        foodCraving: 'あなたはどんな食物を切望しているか？',
        username: 'ユーザーネーム',
        emailAddress: '電子メールアドレス',
        location: '位置',
        oldPassword: '古いパスワード',
        newPassword: '新しいパスワード',
        newPasswordRepeat: '新しいパスワード（繰り返し）',
        notifyMe: '私に通知しなさい…',
        likesPicture: '誰かは私の写真が好き…',
        addsToEatingOutPicture: '誰かが食べるリストへの私の写真を追加する',
        sharesPicture: '誰かが私の写真を共有する',
        startsFollowing: '誰かが私をフォローする',
        saveChanges: '変更を保存しなさい',
        list: 'リスト',
        map: 'マップ',
        noEatingOut: '皿をあなたのリストに追加しなかった 。まさに、そうするために、刃物類アイコンをクリックしなさい！',
        welcomeTo: 'するために歓迎します',
        tastemateDescription: 'あなたの料理の経験を他と共有する場所',
        getEating: '私達を、食べ始めさせなさい！',
        signUp: 'サインアップ',
        logIn: 'ログイン',
        password: 'パスワード',
        noAccount: 'まだアカウントを持っていませんか？ここにサインアップしなさい！',
        alreadyAccount: 'すでにアカウントを持ってますか ？ここにログインしなさい',
        skip: 'スキップ',
        errorMessageEnterUsername: 'どうぞ、ユーザーネームに入力してください。',
        errorMessageEnterEmail: 'どうぞ、電子メールアドレスを入力してください。',
        errorMessageEnterPassword: 'どうぞ、パスワードを入力してください。',
        errorMessageEnterLocation: 'どうぞ、位置に入ってください。',
        errorMessageInvalidEmail: 'あなたが入力した電子メールアドレスは無効である。',
        errorMessageUserDisabled: 'この電子メールアドレスと関連したアカウントは使用不可にされた。',
        errorMessageUserNotFound: 'この電子メールアドレスと関連したアカウントがない。',
        errorMessageWrongPassword: 'あなたが入力したパスワードは不正確である。',
        errorMessageWeakPassword: 'あなたが入力したパスワードは弱すぎる。',
        errorMessageEmailAlreadyInUse: 'この電子メールアドレスはすでに{0}アカウントに接続している。',
        next: '次に',
        previous: '前',
        publish: '出版しなさい',
        description: '説明',
        dishname: '皿名',
        price: '価格',
        rateExperience: 'あなたはどのようにあなたの全体の経験を評価するか？',
        currency: '通貨',
        selectCurrency: 'あなたの価格の通貨を選択して下さい',
        searchVocabulary: '味、テクスチャー、およびにおいはどうか ?',
        noLocationResults: 'どのマッチングする場所が見つからなかった どうぞ、より多くの情報を入力してください 。',
        yes: 'はい',
        no: 'いいえ',
        ok: 'OK',
        openSettings: '開いている設定',
        accessCameraQuestion: '私達はあなたのカメラにアクセスできるか？',
        accessCameraExplanation: '私達は、あなたがあなたの食物の写真をとり、共有できるようにアクセスする必要がある。',
        accessPhotoQuestion: '私達はあなたの写真ロールにアクセスできるか？',
        accessPhotoExplanation: '私達は、あなたがあなたの食物の写真を選び、共有できるようにアクセスする必要がある。',
        enableCamera: 'どうぞ、あなたの電話の{0}設定において、カメラを許可しこの機能を使うことを可能にしてください。',
        enablePhoto: 'どうぞ、あなたの電話の{0}設定において、ストレージの許可がこの機能を使うことを可能にしてください。',
        enableCameraAndPhoto: '写真をアップロードするためには、私達は最初、あなたのカメラとカメラロールにアクセスする必要がある。どうぞ、許可ダイアログを開くためにここをクリックしてください！代わりに、あなたはあなたのスマートフォンの{0}設定に行き、そこに許可を与えることができる。',
        permissionDenied: '許可が否定される',
        mypocExplanationTitle: 'MyPoCテキストフィールド',
        mypocExplanationText: 'このフィールドは、私達のMyPoCシステムにより予測されるように一般皿名を表示する。もし予測が不正確ならば、名前を編集しなさい！',
        more: 'より多く',
        accessLocationQuestion: '私達はあなたの位置にアクセスできるか？',
        accessLocationExplanation: '私達は、あなたが、近くで、保存された観察がであるかをわかることができるようにアクセスする必要がある。',
        enableLocation: 'どうぞ、あなたの電話の{0}設定において、位置許可がこの機能を使うことを可能にしてください。',
        editObservation: '観察を編集',
        save: '保存',
        errorMessageUsernameAlreadyInUse: 'このユーザー名は既にTestemateアカウントに接続されています',
        commentsSg: '{0} コメント',
        comments: '{0} コメント',
        commentedPicture: '{0} あなたの画像に関してコメントしました',
        allComments: '全てのコメント',
        missingValuesTitle: '欠けている価',
        missingValuesTextSg: '印刷する前にあなたの皿の{0}を追加してください.',
        missingValuesTextPl: '印刷する前にあなたの皿の {0} と{1}を追加してください',
        itemization: '{0}, {1}',
        picture: '写真',
        tasteTerms: '1テイストの条件',
        lessThanKm: '{0}kmより短く',
        furtherAway: 'さらに遠く',
        noEatingOutList: 'イーティングアウトリストに何も追加したくなければ、観察の横にある刃物のアイコンをクリックしてリストに追加してください',
        noNotifications: 'あなたはまだ何も通知をもらってません',
        noImages: 'あなたのカメラロールが空のようなので代わりに写真を撮ってください',
        checkingUsername: 'ユーザーネームを取得しているか確認...',
        creatingAccount: 'アカウント作成...',
        savingUserInformation: 'あなたの情報を保存...',
        loggingIn: 'ログイン...',
        creatingAnonymous: '匿名アカウントを作成...',
        savingObservation: '観察を保存...',
        savingProfile: 'プロフィールを保存...',
        uploadingPicture: '写真をアップロード...',
        unknownLocation: '不明のロケーション',
        loading: 'ローディング...',
        errorOccurred: 'エラーが発生しました。後でもう一度やってください',
        noSearchResults: 'あなたの検索に該当する観察はありません。他の検索を入力してください',
        viewMoreComments: 'もっとコメントをみる',
        flavor: 'フレーバー',
        odor: 'におい',
        texture: 'テクスチャー',
        selected: '選択済み',
        noMatchingTerms: 'あなたの検索に該当する用語はありません',
        noSelectedTerms: '下方にある用語の一つをクリックしてあなたの観察に追加しなさい',
        myPoc: 'MyPocの予想: {0}',
        all: 'すべて',
        dietaryInfo: '栄養情報',
        homemade: '自家製',
        eatingOut: '外食',
        viewAttributions: '属性を見る',
        attributions: '属性',
        predictionLoading: 'MyPocからの提案をロードディングする',
        mypocPrediction: 'MyPocからの提案',
        exitCreateAlertTitle: '下書きを保存しますか？',
        exitCreateAlertMessage: 'あなたはクリエーションスクリーンを閉じようとしています。今の状態を下書きとして保存したいですか？',
        discard: '不一致',
        saveDraft: '下書きを保存',
        deleteDraftAlertTitle: '下書きを削除しますか？',
        deleteDraftAlertMessage: '本当にこの下書きを削除しますか？一旦削除したものは取り消すことはできません',
        deleteDraft: '下書きを削除',
        noDrafts: 'どの観察も下書きとして保存しませんでした',
        readMore: '詳細を読んでください',
        hide: '隠す',
        noInternetAlertTitle: 'インターネット接続ができません',
        noInternetAlertMessage: 'どうかあなたの電話をインターネットに接続してください',
        basil: 'バジル',
        bitter: '苦い',
        bitterSweet: 'ほろ苦い',
        burnt: '燃え尽きる',
        cinnamon: 'シナモン',
        coriander: 'コリアンダー',
        cumin: 'クミン',
        dill: 'ディル',
        fishy: '魚のような',
        floral: '花',
        fresh: '新鮮な',
        fruity: 'フルーティー',
        garlic: 'ニンニク',
        gingery: 'ギンギリ',
        lemon: 'レモン',
        nutmeg: 'ナツメグ',
        nutty: 'ナッティ',
        oily: '油性',
        oniony: 'オニオン',
        orange: 'オレンジ',
        paprika: 'パプリカ',
        parsley: 'パセリ',
        pepper: 'コショウ',
        rosemary: 'ローズマリー',
        salty: '塩辛い',
        sour: 'サワー',
        spicy: 'スパイシー',
        sweet: '甘い',
        umami: 'うま味',
        vanilla: 'バニラ',
    },
    pt: {
        home: 'Home',
        explore: 'Explorar',
        notifications: 'Notificações',
        eatingOutList: 'Eating Out List',
        profile: 'Perfil',
        settings: 'Configurações',
        observationDetail: 'Detalhe',
        createObservation: 'Criar observação',
        signUpLogIn: 'Cadastre-se Log In',
        mapDetail: 'Detalhe do mapa',
        hiThere: 'Ol,',
        welcomeToTastemate: 'Bem-vindo ao {0}!',
        limitedContentExplanation: 'Infelizmente, você não está logado, então só podemos mostrar conteúdo e funcionalidade limitados. Quando estiver pronto para explorar mais o aplicativo, clique no botão do ícone do usuário no canto superior esquerdo para fazer login ou criar uma nova conta. Enquanto isso,',
        haveFun: 'Divirta-se!',
        emptyFeed: 'Parece que seu feed está vazio. Por que não seguir alguns {0}s?',
        selectAction: 'Selecione uma ação',
        share: 'Compartilhe',
        edit: 'Editar',
        delete: 'Excluir',
        cancel: 'Cancelar',
        shareDialogTitle: 'Onde você deseja compartilhar este post?',
        shareSubject: 'Sugestões {0}',
        shareMessage: 'Veja este prato incrÌvel no {0}!',
        likes: '{0} likes',
        shares: '{0} compartilhamentos',
        cutleries: '{0} talheres',
        likesSg: '{0} like',
        sharesSg: '{0} compartilhar',
        cutleriesSg: '{0} talheres',
        thousand: '{0}k',
        million: '{0}m',
        writeComment: 'Escrever um comentário ...',
        close: 'Fechar',
        likedPicture: '{0} gostou da sua foto. // e.g. Lukas liked your picture.',
        sharedPicture: '{0} compartilhou sua foto.',
        addedToEatingOutPicture: '{0} adicionou sua foto à lista Comendo Fora.',
        startedFollowing: '{0} começou a seguir você.',
        userAndUser: '{0} e {1}',
        others: '{0} outros',
        photos: 'Fotos',
        followers: 'Seguidores',
        following: 'Seguindo',
        noPictures: 'Este usuário não adicionou nenhuma foto.',
        noUsers: 'Nenhum usu·rio para exibir.',
        foodCraving: 'Que comida você está desejando?',
        username: 'username',
        emailAddress: 'endereÁo de email',
        location: 'localização',
        oldPassword: 'senha antiga',
        newPassword: 'nova senha',
        newPasswordRepeat: 'nova senha (repitir)',
        notifyMe: 'Notifique-me quando ...',
        likesPicture: 'alguém gosta da minha foto',
        addsToEatingOutPicture: 'alguém adiciona minha foto à sua lista de Comendo Fora',
        sharesPicture: 'alguém compartilha minha foto',
        startsFollowing: 'alguém começa a me seguir',
        saveChanges: 'Salvar alterações',
        list: 'Lista',
        map: 'Mapa',
        noEatingOut: 'Parece que você não adicionou um prato à sua lista. Basta clicar no ícone de talheres para fazer isso!',
        welcomeTo: 'Bem-vindo ao',
        tastemateDescription: 'o lugar para compartilhar suas experiências culinárias com os outros',
        getEating: 'Vamos comer!',
        signUp: 'Inscrever-se',
        logIn: 'Entrar',
        password: 'senha',
        noAccount: 'Ainda não tens uma conta? Assine aqui!',
        alreadyAccount: 'Já tem uma conta? Entre aqui!',
        skip: 'pular',
        errorMessageEnterUsername: 'Por favor digite um nome de usuário.',
        errorMessageEnterEmail: 'Por favor insira um endereÁo de email.',
        errorMessageEnterPassword: 'Por favor digite uma senha.',
        errorMessageEnterLocation: 'Por favor, digite um local.',
        errorMessageInvalidEmail: 'O endereço de e-mail digitado é inválido.',
        errorMessageUserDisabled: 'A conta associada a este endereço de email foi desativada.',
        errorMessageUserNotFound: 'Não há uma conta associada a este endereço de e-mail.',
        errorMessageWrongPassword: 'A senha que você digitou está incorreta.',
        errorMessageWeakPassword: 'A senha que você digitou é muito fraca.',
        errorMessageEmailAlreadyInUse: 'Este endereço de e-mail já está conectado a uma conta {0}.',
        next: 'PrÛximo',
        previous: 'Anterior',
        publish: 'Publicar',
        description: 'descrição',
        dishname: 'nome do prato',
        price: 'preço',
        rateExperience: 'Como você avaliaria sua experiência geral?',
        currency: 'Moeda',
        selectCurrency: 'Por favor, selecione a moeda do preço que você indicou.',
        searchVocabulary: 'Qual foi o sabor, textura e odor do prato?',
        noLocationResults: 'Nenhum local correspondente encontrado, digite mais informações.',
        yes: 'Sim',
        no: 'Não',
        ok: 'OK',
        openSettings: 'Abrir configurações',
        accessCameraQuestion: 'Podemos acessar sua câmera?',
        accessCameraExplanation: 'Precisamos de acesso para que vocÍ possa tirar e compartilhar fotos de sua comida.',
        accessPhotoQuestion: 'Podemos acessar seu rolo de fotos?',
        accessPhotoExplanation: 'Precisamos de acesso para que você possa selecionar e compartilhar fotos de sua comida.',
        enableCamera: 'Por favor habilite a permissão da câmera nas configurações do {0} do seu telefone para usar este recurso.',
        enablePhoto: 'Por favor, ative a permissão de armazenamento nas configurações do {0} do seu telefone para usar este recurso.',
        enableCameraAndPhoto: 'Para fazer upload de uma foto, primeiro precisamos acessar sua câmera e o rolo da câmera. Por favor clique aqui para abrir a janela de permissão! Alternativamente, você pode ir para as configurações do {0} do seu smartphone e lá conceder as permissões.',
        permissionDenied: 'Permissão negada',
        mypocExplanationTitle: 'Campo de texto do MyPoC',
        mypocExplanationText: 'Este campo exibe um nome geral do prato conforme previsto pelo nosso sistema MyPoC. Sinta-se à vontade para editar o nome se a previsão estiver incorreta!',
        more: 'Mais',
        accessLocationQuestion: 'Podemos acessar sua localização?',
        accessLocationExplanation: 'Precisamos de acesso para que você possa ver as observações salvas próximas.',
        enableLocation: 'Por favor, ative a permissão de localização nas configurações do {0} do seu telefone para usar este recurso.',
    },
    ta /*tamil*/: {
        home: 'முகப்பு',
        explore: 'ஆய்வு செய்',
        notifications: 'அறிவிப்பு',
        eatingOutList: 'வெளியே உண்ணும் பட்டியல்',
        profile: 'சுயவிவரம்',
        settings: 'அமைப்புகள்',
        observationDetail: 'விவரம்',
        createObservation: 'கவனிப்பு உருவாக்கம்',
        signUpLogIn: 'உள்நுழைய பதிவு',
        mapDetail: 'வரைபட விவரங்கள்',
        hiThere: 'வணக்கம்',
        welcomeToTastemate: '{0} க்கு வரவேற்கிறோம்!',
        limitedContentExplanation: 'எதிர்பாராதவிதமாக, நீங்கள் உள்நுழைந்திருக்கவில்லை, அதனால் நாங்கள் உங்களுக்கு குறிப்பிட்ட உள்ளடக்கம் மற்றும் செயல்பாட்டை மட்டுமே காண்பிக்க முடியும். நீங்கள் பயன்பாட்டை மேலும் ஆராய தயாரானவுடன், உள்நுழைவதற்கு மேல் இடது மூலையில் உள்ள பயனரின் ஐகானைக் கிளிக் செய்யவும் அல்லது புதிய கணக்கை உருவாக்கவும். இதற்கிடையில்',
        haveFun: 'அனுபவி!',
        emptyFeed: 'உங்கள் ஊட்டம் காலியாக உள்ளது போல் தெரிகிறது. ஏன் சில {0}s ஐ பின்பற்றக்கூடாது?',
        selectAction: 'ஒரு செயலைத் தேர்ந்தெடுக்கவும்',
        doWithPost: 'இந்த இடுகையில் நீங்கள் என்ன செய்ய விரும்புகிறீர்கள்?',
        share: 'பகிர்',
        edit: 'தொகு',
        delete: 'நீக்கு',
        cancel: 'ரத்து',
        shareDialogTitle: 'இந்த இடுகையை எங்கே பகிர்ந்து கொள்ள விரும்புகிறீர்கள்?',
        shareSubject: '{0}ல் கூலான டிஷ்',
        shareMessage: '{0}ல் இந்த அற்புதமான உணவை பாருங்கள்!',
        likes: '{0} விருப்பு',
        shares: '{0} பகிர்வுகள்',
        cutleries: '{0} வெட்டுக்கருவிகள்',
        likesSg: '{0} விருப்பம்',
        sharesSg: '{0} பகிர்',
        cutleriesSg: '{0} கருவிகள்',
        thousand: '{0} k',
        million: '{0} m',
        writeComment: 'கருத்துரை எழுதவும்…',
        close: 'மூடு',
        likedPicture: '{0} உங்கள் படம் பிடித்திருந்தது.',
        sharedPicture: '{0} உங்கள் படத்தை பகிர்ந்துள்ளனர்.',
        addedToEatingOutPicture: '{0} உங்கள் படத்தை தங்கள் வெளியே உண்ணும் பட்டியலில் சேர்க்கப்பட்டது.',
        startedFollowing: '{0} உங்களைப் பின்தொடரத் தொடங்கியுள்ளனர்.',
        userAndUser: '{0} மற்றும் {1}',
        others: '{0} மற்றவைகள்',
        photos: 'புகைப்படங்கள்',
        followers: 'பின்பற்றுபவர்கள்',
        following: 'பின்பற்றுதல்',
        noPictures: 'இந்த பயனர் எந்த படங்களையும் சேர்க்கவில்லை.',
        noUsers: 'காண்பிக்க பயனர்கள் இல்லை.',
        foodCraving: 'நீங்கள் எந்த உணவை விரும்புகிறீர்கள்?',
        username: 'பயனர்பெயர்',
        emailAddress: 'மின்னஞ்சல் முகவரி',
        location: 'இருப்பிடம்',
        oldPassword: 'பழைய கடவுச்சொல்',
        newPassword: 'புதிய கடவுச்சொல்',
        newPasswordRepeat: 'புதிய கடவுச்சொல் (மீண்டும்)',
        notifyMe: 'எப்போது எனக்கு தெரியப்படுத்து',
        likesPicture: 'யாராவது என் படத்தை விரும்பினால்',
        addsToEatingOutPicture: 'யாராவது என் படத்தை தங்கள் வெளியே உண்ணும் பட்டியலில் சேர்த்திருந்தால்',
        sharesPicture: 'யாராவது என் படத்தை பகிர்ந்து இருந்தால்',
        startsFollowing: 'யாராவது என்னை பின்தொடரத் தொடங்கினால்',
        saveChanges: 'மாற்றங்களைச் சேமிக்கவும்',
        list: 'பட்டியல்',
        map: 'வரைபடம்',
        noEatingOut: 'நீங்கள் உங்கள் பட்டியலில் எந்த உணவையும் சேர்க்கவில்லை போல் தெரிகிறது. அவ்வாறு செய்ய கருவி ஐகானைக் கிளிக் செய்யவும்!',
        welcomeTo: 'வரவேற்கிறோம்',
        tastemateDescription: 'இது உங்கள் சமையல் அனுபவங்களை மற்றவர்களுடன் பகிர்வதற்கான இடம்',
        getEating: 'சாப்பிடுவோம்',
        signUp: 'பதிவு செய்க',
        logIn: 'உள் நுழை',
        password: 'கடவுச்சொல்',
        noAccount: 'இன்னும் ஒரு கணக்கு இல்லையா? இங்கே பதிவு செய்க!',
        alreadyAccount: 'ஏற்கனவே ஒரு கணக்கு உள்ளதா? இங்கே உள்நுழைக!',
        skip: 'தவிர்',
        errorMessageEnterUsername: 'தயவு செய்து ஒரு பயனர்பெயரை உள்ளிடவும்.',
        errorMessageEnterEmail: 'தயவு செய்து ஒரு மின்னஞ்சல் முகவரியை உள்ளிடவும்.',
        errorMessageEnterPassword: 'தயவு செய்து ஒரு கடவுச்சொல்லை உள்ளிடவும்.',
        errorMessageEnterLocation: 'தயவு செய்து ஒரு இருப்பிடத்தை உள்ளிடவும்.',
        errorMessageInvalidEmail: 'நீங்கள் உள்ளிட்ட மின்னஞ்சல் முகவரி தவறானது.',
        errorMessageUserDisabled: 'இந்த மின்னஞ்சல் முகவரியுடன் தொடர்புடைய கணக்கு முடக்கப்பட்டுள்ளது.',
        errorMessageUserNotFound: 'இந்த மின்னஞ்சல் முகவரியுடன் தொடர்புடைய கணக்கு எதுவும் இல்லை.',
        errorMessageWrongPassword: 'நீங்கள் உள்ளிட்ட கடவுச்சொல் தவறானது.',
        errorMessageWeakPassword: 'நீங்கள் உள்ளிட்ட கடவுச்சொல் மிகவும் பலவீனமாக உள்ளது.',
        errorMessageEmailAlreadyInUse: 'இந்த மின்னஞ்சல் முகவரி ஏற்கனவே {0} கணக்கில் இணைக்கப்பட்டுள்ளது.',
        next: 'அடுத்து',
        previous: 'முந்தின',
        publish: 'வெளியிடு',
        description: 'விளக்கம்',
        dishname: 'உணவு பெயர்',
        price: 'விலை',
        rateExperience: 'உங்கள் ஒட்டுமொத்த அனுபவத்தை எப்படி நீங்கள் மதிப்பிடுவீர்கள்?',
        currency: 'நாணய',
        selectCurrency: 'நீங்கள் குறிப்பிட்ட விலையில் நாணயத்தைத் தேர்ந்தெடுக்கவும்.',
        searchVocabulary: 'உணவின் சுவை, அமைப்பு மற்றும் வாசனை என்ன?',
        noLocationResults: 'பொருத்தமான இடம் இல்லை, மேலும் தகவலை உள்ளிடவும்.',
        yes: 'ஆம்',
        no: 'இல்லை',
        ok: 'சரி',
        openSettings: 'திறந்த அமைப்புகள்',
        accessCameraQuestion: 'உங்கள் கேமராவை அணுகலாமா?',
        accessCameraExplanation: 'எங்களுக்கு அணுகல் தேவை அதனால் நீங்கள் உங்கள் உணவுப் படங்களை எடுத்துக் கொள்ளவும், பகிர்ந்து கொள்ளவும் முடியும்.',
        accessPhotoQuestion: 'உங்கள் புகைப்பட ரோலை அணுகலாமா?',
        accessPhotoExplanation: 'எங்களுக்கு அணுகல் தேவை அதனால் நீங்கள் உங்கள் உணவுத் படங்களை தேர்ந்தெடுத்து பகிர்ந்து கொள்ளலாம்',
        enableCamera: 'இந்த அம்சத்தை பயன்படுத்த உங்கள் தொலைபேசியின் {0} அமைப்புகளில் கேமரா அனுமதியை இயக்கவும்',
        enablePhoto: 'இந்த அம்சத்தைப் பயன்படுத்த உங்கள் தொலைபேசியின் {0} அமைப்புகளில் சேமிப்பிட அனுமதியை இயக்கவும்',
        enableCameraAndPhoto: 'படத்தைப் பதிவேற்ற, முதலில் உங்கள் கேமரா மற்றும் கேமரா ரோலுக்கான அணுகல் தேவை. அனுமதி உரையாடலைத் திறக்க இங்கே கிளிக் செய்க! மாற்றாக, உங்கள் ஸ்மார்ட்போனின் {0} அமைப்புகளுக்குச் சென்று, அங்கு அனுமதிகளை வழங்கலாம்.',
        permissionDenied: 'அனுமதி மறுக்கப்பட்டது',
        mypocExplanationTitle: 'MyPoC உரை புலம்',
        mypocExplanationText: 'எமது MyPoC அமைப்பின் கணிப்புப்படி இந்த புலம் ஒரு பொதுவான டிஷ் பெயரைக் காட்டுகிறது. கணிப்பு தவறானது என்றால் பெயரை திருத்தலாம்!',
        more: 'மேலும்',
        accessLocationQuestion: 'உங்கள் இருப்பிடத்தை நாங்கள் அணுகலாமா?',
        accessLocationExplanation: 'அணுகல் தேவை எனவே நீங்கள் அருகிலுள்ள சேமிக்கப்பட்ட கண்காணிப்புகளைக் காணலாம்.',
        enableLocation: 'இந்த அம்சத்தைப் பயன்படுத்த, உங்கள் ஃபோனின் {0} அமைப்புகளில் இருப்பிட அனுமதியை இயக்கவும்.',
        editObservation: 'கவனிப்பைத் திருத்தவும்',
        save: 'சேமிக்கவும்',
        errorMessageUsernameAlreadyInUse: 'இந்த பயனர்பெயர் ஏற்கனவே ஒரு {0} கணக்கில் இணைக்கப்பட்டுள்ளது.',
        commentsSg: '{0} கருத்து',
        comments: '{0} கருத்துகள்',
        commentedPicture: '{0} உங்கள் படத்தில் கருத்து தெரிவித்துள்ளனர்.',
        allComments: 'எல்லா கருத்துகளும்',
        missingValuesTitle: 'விட்டுப்போன மதிப்புகள்',
        missingValuesTextSg: 'அதை வெளியிடுவதற்கு முன் உங்கள் டிஷ் இன் {0} ஐ சேர்க்கவும்.',
        missingValuesTextPl: 'அதை வெளியிடுவதற்கு முன் உங்கள் டிஷ் இன் {0} மற்றும் {1} ஐ சேர்க்கவும்.',
        itemization: '{0}, {1}',
        picture: 'படம்',
        tasteTerms: '1 சுவை சொல்',
        lessThanKm: '{0} கிமீ தொலைவில் உள்ளது',
        furtherAway: 'சற்றுத் தொலைவிலுள்ளது',
        noEatingOutList: 'நீங்கள் உங்கள் வெளியே உண்ணும் பட்டியலில் எதையும் சேர்க்கவில்லை போலத் தெரிகிறது. அதை பட்டியலில் சேர்ப்பதற்கு கவனிப்புக்கு அடுத்த கருவி ஐகானை கிளிக் செய்யவும்!',
        noNotifications: 'இன்னும் உங்களிடம் எந்த அறிவிப்புகளும் இல்லை.',
        noImages: 'உங்கள் கேமரா ரோல் காலியாக உள்ளது போல் தெரிகிறது. பதிலாக படம் எடுக்க முயற்சிக்கவும்.',
        checkingUsername: 'பயனர்பெயர் ஏற்கனவே உள்ளதா எனச் சோதிக்கிறது …',
        creatingAccount: 'உங்கள் கணக்கை உருவாக்குகிறது…',
        savingUserInformation: 'உங்கள் தகவலைச் சேமிக்கிறது…',
        loggingIn: 'உள்நுழைகிறது…',
        creatingAnonymous: 'ஒரு அநாமதேய கணக்கை உருவாக்குகிறது ...',
        savingObservation: 'அவதானிப்புகள் சேமிக்கப்படுகிறது ...',
        savingProfile: 'சுயவிவரத்தைச் சேமிக்கிறது…',
        uploadingPicture: 'பதிவேற்றும் படம்…',
        unknownLocation: 'அறியப்படாத இருப்பிடம்',
        loading: 'ஏற்றுகிறது…',
        errorOccurred: 'ஒரு பிழை ஏற்பட்டது. தயவு செய்து மீண்டும் முயற்சிக்கவும்',
        noSearchResults: 'உங்கள் தேடலுடன் ஒப்பிடும் எந்தவொரு அவதானிப்புகளும் இல்லை. வேறு ஏதேனும் உள்ளிடுக.',
        viewMoreComments: 'மேலும் கருத்துகளைப் பார்க்கவும்',
        flavor: 'சுவை',
        odor: 'வாசனை',
        texture: 'அமைப்பு',
        selected: 'தேர்ந்தெடுக்கப்பட்டது',
        noMatchingTerms: 'உங்கள் தேடலுடன் பொருந்தக்கூடிய சொற்ககள் எதுவும் இல்லை.',
        noSelectedTerms: 'உங்கள் கவனிப்புக்குச் சேர்க்க, கீழே உள்ள சொற்களில் ஒன்றைக் கிளிக் செய்க.',
        myPoc: 'MyPoC கணிப்பு: {0}',
        all: 'அனைத்தும்',
        dietaryInfo: 'உணவு தகவல்',
        homemade: 'வீட்டில் தயாரிக்கப்பட்டது',
        eatingOut: 'வெளியே உண்கிறோம்',
        viewAttributions: 'பண்புகளை காண்க',
        attributions: 'பண்புகள்',
        predictionLoading: 'MyPoC கணிப்பு ஏற்றுகிறது ...',
        mypocPrediction: 'MyPoC கணிப்பு',
        exitCreateAlertTitle: 'வரைவாக சேமிக்கவா?',
        exitCreateAlertMessage: 'நீங்கள் உருவாக்கம் திரையில் இருந்து வெளியேற இருக்கிறீர்கள். உங்கள் தற்போதைய முன்னேற்றத்தை வரைவாக சேமிக்க விரும்புகிறீர்களா?',
        discard: 'நிராகரிக்கலாம்',
        saveDraft: 'வரைவை சேமிக்கவும்',
        deleteDraftAlertTitle: 'வரைவை நீக்கவா?',
        deleteDraftAlertMessage: 'நிச்சயமாக இந்த வரைவு நீக்க வேண்டுமா?இந்த நடவடிக்கை திரும்பப்பெற முடியாததாகும்.',
        deleteDraft: 'வரைவை நீக்கவும்',
        noDrafts: 'வரைவுகளாக நீங்கள் எந்த அவதானிப்புகளையும் சேமிக்கவில்லை.',
        readMore: 'மேலும் வாசிக்க',
        hide: 'மறை',
        noInternetAlertTitle: 'இணைய இணைப்பு இல்லை',
        noInternetAlertMessage: 'தொடர்வதற்கு, இணையத்துடன் உங்கள் தொலைபேசி இணைக்கவும்..',
        unknownUsername: 'தெரியாத பயனர்பெயர்',
        kFollowers: '{0} பின்பற்றுபவர்கள்',
        kFollowersSg: '{0} பின்பற்றுபவர்',
        clickHereToRefresh: 'புதுப்பிக்க இங்கே கிளிக் செய்யவும்!',
        noInternet: 'நீங்கள் இணையத்துடன் இணைக்கப்படாததுபோல் தெரிகிறது. சமீபத்திய தரவைப் பெற இணையத்துடன் இணைக்கவும்.',
        tryAgain: 'மீண்டும் முயற்சி செய்',
    },
    de: {
        home: 'Home',
        explore: 'Entdecken',
        notifications: 'Mitteilungen',
        eatingOutList: 'Essensliste',
        profile: 'Profil',
        settings: 'Einstellungen',
        observationDetail: 'Detail',
        createObservation: 'Erstelle Posting',
        signUpLogIn: 'Anmelden Einloggen',
        mapDetail: 'Karte',
        hiThere: 'Hallo,',
        welcomeToTastemate: 'Willkommen bei {0}!',
        limitedContentExplanation: 'Leider bist du noch nicht eingeloggt und wir können dir deshalb nur eingeschränkte Inhalte und Funktionalitäten anzeigen. Sobald du bereit bist, mehr von der App zu sehen, kannst du einfach den Benutzer-Button links oben klicken und dich anzumelden oder einzuloggen. Bis dahin,',
        haveFun: 'Viel Spaß!',
        emptyFeed: 'Sieht so aus, als ob dein Feed leer ist. Warum folgst du nicht einfach einen paar {0}s?',
        selectAction: 'Wähle eine Aktion',
        doWithPost: 'Was würdest du gerne mit diesem Post machen?',
        share: 'Teilen',
        edit: 'Bearbeiten',
        delete: 'Löschen',
        cancel: 'Abbrechen',
        shareDialogTitle: 'Wo möchtest du diesen Post teilen?',
        shareSubject: 'Cooles Gericht auf {0}!',
        shareMessage: 'Schau dir dieses coole Gericht auf {0} an!',
        likes: '{0} Likes',
        shares: '{0} Teilungen',
        cutleries: '{0} Bestecke',
        likesSg: '{0} Like',
        sharesSg: '{0} Teilung',
        cutleriesSg: '{0} Besteck',
        thousand: '{0}k',
        million: '{0}m',
        writeComment: 'Schreibe einen Kommentar...',
        close: 'Schließen',
        likedPicture: '{0} hat dein Bild geliket.',
        sharedPicture: '{0} hat dein Bild geteilt.',
        addedToEatingOutPicture: '{0} hat dein Bild seiner Essensliste hinzugefügt.',
        startedFollowing: '{0} hat angefangen, dir zu folgen.',
        userAndUser: '{0} und {1}',
        others: '{0} Andere',
        photos: 'Fotos',
        followers: 'Folgende',
        following: 'Gefolgte',
        noPictures: 'Dieser Benutzer hat noch keine Bilder hochgeladen.',
        noUsers: 'Es gibt keine Benutzer zum Anzeigen.',
        foodCraving: 'Nach welchem Essen sehnst du dich?',
        username: 'Nutzername',
        emailAddress: 'E-Mail-Adresse',
        location: 'Ort',
        oldPassword: 'Altes Passwort',
        newPassword: 'Neues Passwort',
        newPasswordRepeat: 'Neues Passwort (erneut)',
        notifyMe: 'Benachrichtige mich, wenn...',
        likesPicture: 'jemand mein Bild liket',
        addsToEatingOutPicture: 'jemand mein Bild zu seiner Essensliste hinzufügt.',
        sharesPicture: 'jemand mein Bild teilt',
        startsFollowing: 'jemand anfängt, mir zu folgen.',
        saveChanges: 'Änderungen speichern',
        list: 'Liste',
        map: 'Karte',
        noEatingOut: 'Sieht so aus, als ob du noch keine Gerichte zu deiner Essensliste hinzugefügt hättest. Klicke einfach auf das Besteck-Icon, um dies zu tun!',
        welcomeTo: 'Willkommen bei',
        tastemateDescription: 'der Ort, an dem du deine kulinarischen Erlebnisse mit anderen teilen kannst',
        getEating: 'Guten Appetit!',
        signUp: 'Anmelden',
        logIn: 'Einloggen',
        password: 'Passwort',
        noAccount: 'Du hast noch kein Benutzerkonto? Melde dich hier an!',
        alreadyAccount: 'Du hast schon ein Benutzerkonto? Logge dich hier ein!',
        skip: 'Überspringen',
        errorMessageEnterUsername: 'Bitte trage einen Nutzernamen ein.',
        errorMessageEnterEmail: 'Bitte trage eine E-Mail-Adresse ein.',
        errorMessageEnterPassword: 'Bitte trage ein Passwort ein.',
        errorMessageEnterLocation: 'Bitte trage einen Ort ein.',
        errorMessageInvalidEmail: 'Die E-Mail-Adresse, die du angegeben hast, ist ungültig.',
        errorMessageUserDisabled: 'Das Benutzerkonto, dass mit dieser E-Mail-Adresse verknüpft ist, wurde deaktiviert.',
        errorMessageUserNotFound: 'Es gibt kein Benutzerkonto unter dieser E-Mail-Adresse.',
        errorMessageWrongPassword: 'Das Passwort ist ungültig.',
        errorMessageWeakPassword: 'Das Passwort ist zu schwach.',
        errorMessageEmailAlreadyInUse: 'Diese E-Mail-Adresse ist bereits mit einem {0}-Benutzerkonto verknüpft.',
        next: 'Weiter',
        previous: 'Zurück',
        publish: 'Veröffentlichen',
        description: 'Beschreibung',
        dishname: 'Name des Gerichts',
        price: 'Preis',
        rateExperience: 'Wie würdest du das gesamte Erlebnis bewerten?',
        currency: 'Währung',
        selectCurrency: 'Bitte wähle die Währung des Gericht aus.',
        searchVocabulary: 'Wie waren der Geschmack, die Konsisteny und der Geruch des Gerichts?',
        noLocationResults: 'Es wurde kein passender Ort gefunden, bitte trage mehr Informationen ein.',
        yes: 'Ja',
        no: 'Nein',
        ok: 'Ok',
        openSettings: 'Einstellungen öffnen',
        accessCameraQuestion: 'Dürfen wir auf deine Kamera zugreifen?',
        accessCameraExplanation: 'Wir brauchen Zugriff auf deine Kamera, damit du Fotos deiner Gerichte machen und teilen kannst.',
        accessPhotoQuestion: 'Dürfen wir auf deine Fotos zugreifen?',
        accessPhotoExplanation: 'Wir brauchen Zugriff auf deine Fotos, damit du deine Gerichte mit anderen teilen kannst.',
        enableCamera: 'Bitte schalte die Kamera-Zugriffserlaubnis in den {0}-Einstellungen deines Handys ein, um diese Funktionalität verwenden zu können.',
        enablePhoto: 'Bitte schalte die Aufbewahrungs-Zugriffserlaubnis in den {0}-Einstellungen deines Handys ein, um diese Funktionalität verwenden zu können.',
        enableCameraAndPhoto: 'Um ein Bild hochladen zu können, brauchen wir erst Zugriff auf deine Kamera und auf deine Fotos. Bitte klicke hier, um das Dialogfenster zu öffnen. Ansonsten kannst du auch in die {0}-Einstellungen deines Handzs gehen und dort die Zugriffserlaubnis einstellen.',
        permissionDenied: 'Erlaubnis verweigert',
        mypocExplanationTitle: 'Das MyPoC-Textfeld',
        mypocExplanationText: 'Diese Feld zeigt einen generellen Namen des Gerichts, erkannt von unserem MyPoC-System. Du kannst diesen generellen Namen jederzeit ändern, wenn er falsch ist!',
        more: 'Mehr',
        accessLocationQuestion: 'Dürfen wir Zugriff auf deinen Standplatz haben?',
        accessLocationExplanation: 'Wir brauchen Zugriff, damit du sehen kansst, welche Gerichte auf deiner Essensliste in der Nähe sind.',
        enableLocation: 'Bitte schalte die Standort-Zugriffserlaubnis in den {0}-Einstellungen deines Handys ein, um diese Funktionalität verwenden zu können.',
        editObservation: 'Post bearbeiten',
        save: 'Speichern',
        errorMessageUsernameAlreadyInUse: 'Dieser Nutzername ist bereits mit einem {0}-Benutzerkonto verknüpft.',
        commentsSg: '{0} Kommentar',
        comments: '{0} Kommentare',
        commentedPicture: '{0} hat dein Bild kommentiert.',
        allComments: 'Alle Kommentare',
        missingValuesTitle: 'Fehlende Werte',
        missingValuesTextSg: 'Bitte füge dies deinem Gericht hinzu, bevor du es veröffentlichst: {0}',
        missingValuesTextPl: 'Bitte füge dies deinem Gericht hinzu, bevor du es veröffentlichst: {0} und {1}',
        itemization: '{0}, {1}',
        picture: 'Bild',
        tasteTerms: '1 Geschmacksbegriff',
        lessThanKm: 'Weniger als {0}km weit entfernt',
        furtherAway: 'Weiter entfernt',
        noEatingOutList: 'Sieht so aus, also ob du deiner Essensliste noch kein Gericht hinzugefügt hast. Klicke einfach auf das GerichtßIcon neben einem Post, um es zu deiner Liste hinzuzufügen!',
        noNotifications: 'Du hast noch keine Mitteilungen.',
        noImages: 'Sieht so aus, also ob du noch keine Fotos gespeichert hast. Versuche stattdessen, ein Foto zu machen.',
        checkingUsername: 'Überprüfe, ob der Nutzername schon in Verwendung ist...',
        creatingAccount: 'Erstelle dein Benutzerkonto...',
        savingUserInformation: 'Speichere deine Informationen...',
        loggingIn: 'Logge dich ein...',
        creatingAnonymous: 'Erstelle ein anonymes Benutzerkonto...',
        savingObservation: 'Speichere Post...',
        savingProfile: 'Speichere Profil...',
        uploadingPicture: 'Lade Bild hoch...',
        unknownLocation: 'Unbekannter Ort',
        loading: 'Lade...',
        errorOccurred: 'Ein Fehler ist aufgetrete. Bitte versuche es später erneut.',
        noSearchResults: 'Es gibt keine Posts, die zu deiner Suche passen. Bitte suche nach etwas anderem.',
        viewMoreComments: 'Mehr Kommentare',
        flavor: 'Geschmack',
        odor: 'Geruch',
        texture: 'Konsistenz',
        selected: 'Ausgewählt',
        noMatchingTerms: 'Es gibt keine Geschmacksbegriffe, die deiner Suche entsprechen.',
        noSelectedTerms: 'Klicke auf einen der unten stehenden Begriffe, um ihn zu deinem Post hinzuzufügen.',
        myPoc: 'MyPoC-Prognose: {0}',
        all: 'Alle',
        dietaryInfo: 'Ernährungsinformationen',
        homemade: 'Selbstgemacht',
        eatingOut: 'Restaurantbesuch',
        viewAttributions: 'Zuschreibungen ansehen',
        attributions: 'Zuschreibungen',
        predictionLoading: 'MyPoC-Prognose wird geladen...',
        mypocPrediction: 'MyPoC-Prognose',
        exitCreateAlertTitle: 'Als Entwurf speichern?',
        exitCreateAlertMessage: 'Du verlässt gerade den Erstellungsdialog. Möchtest du deinen Fortschritt als Entwurf speichern?',
        discard: 'Verwerfen',
        saveDraft: 'Entwurf speichern',
        deleteDraftAlertTitle: 'Entwurf löschen?',
        deleteDraftAlertMessage: 'Bist du sicher, dass du diesen Entwurf löschen möchtest? Das Löschen kann nicht wieder rückgängig gemacht werden.',
        deleteDraft: 'Entwurf löschen',
        noDrafts: 'Du hast noch keine Entwürfe gespeichert.',
        readMore: 'Mehr lesen',
        hide: 'Weniger',
        noInternetAlertTitle: 'Keine Internetverbindung',
        noInternetAlertMessage: 'Bitte verbinde dein Handy mit dem Internet, um fortzufahren.',
        unknownUsername: 'Unbekannter Nutzername',
        kFollowers: '{0} Folgende',
        kFollowersSg: '{0} Folgender',
        clickHereToRefresh: 'Sobald du fertig bist, kannst du einfach hier klicken, um deinen Feed zu aktualisieren!',
        noInternet: 'Sieht so aus, als ob dein Handy nicht mit dem Internet verbunden ist. Bitte verbinde es, damit du die neuesten Daten bekommen kannst',
        tryAgain: 'Erneut versuchen',
        none: 'Keine',
        fruitarian: 'Frutarisch',
        vegetarian: 'Vegetarisch',
        pescatarian: 'Pescetarisch',
        vegan: 'Vegan',
        noLactose: 'Laktosefrei',
        noNut: 'Ohne Nüsse',
        noEgg: 'Ohne Eier',
        noSoy: 'Ohne Soja',
        noFish: 'Ohne Fisch',
        noShellfish: 'Ohne Schalentiere',
        kosher: 'Koscher',
        halal: 'Halal',
        glutenFree: 'Glutenfrei',
        basil: 'Basilikum',
        bitter: 'bitter',
        bitterSweet: 'bittersüß',
        burnt: 'verbrannt',
        cinnamon: 'Zimt',
        coriander: 'Koriander',
        cumin: 'Kreuzkümmel ',
        dill: 'Dill',
        fishy: 'fischig',
        floral: 'blumig',
        fresh: 'frisch',
        fruity: 'fruchtig',
        garlic: 'Knoblauch',
        gingery: 'Ingwer',
        lemon: 'Zitrone',
        nutmeg: 'Muskatnuss',
        nutty: 'nussig',
        oily: 'ölig',
        oniony: 'Zwiebel',
        orange: 'Orange',
        paprika: 'Paprika',
        parsley: 'Petersilie',
        pepper: 'Pfeffer',
        rosemary: 'Rosmarin',
        salty: 'salzig',
        sour: 'sauer',
        spicy: 'scharf',
        sweet: 'süß',
        umami: 'umami',
        vanilla: 'Vanille',
    },
});